"""
Tests for merge_anchor_manifests.py: combines an anchor-set manifest.json with a later
growth run's manifest (new prompt_ids only) without regenerating the original prompts on
GPU. Mirrors pi_level_experiment/merge_manifests.py's approach, adapted to the anchor-set
manifest shape (images keyed by prompt_id, not chains keyed by chain_key).
"""
import pytest

from merge_anchor_manifests import merge_anchor_manifests


def _manifest(model, img_size, images):
    return {"model": model, "candidate_seeds": [42], "img_size": img_size,
            "num_inference_steps": 30, "early_window_fraction": 0.5, "images": images}


def _image(prompt_id):
    return {"prompt_id": prompt_id, "n": 2, "prompt": "x", "subjects": [], "seed": 42,
            "detected": True, "num_people_detected": 2, "image_path": "artifacts/images/x.png",
            "attributes": []}


def test_merge_combines_images_from_both_manifests():
    original = _manifest("sdxl", 1024, [_image(0), _image(1)])
    growth = _manifest("sdxl", 1024, [_image(18), _image(19)])
    merged = merge_anchor_manifests([original, growth])
    assert sorted(img["prompt_id"] for img in merged["images"]) == [0, 1, 18, 19]


def test_merge_preserves_shared_metadata():
    original = _manifest("sdxl", 1024, [_image(0)])
    growth = _manifest("sdxl", 1024, [_image(18)])
    merged = merge_anchor_manifests([original, growth])
    assert merged["model"] == "sdxl"
    assert merged["img_size"] == 1024


def test_merge_rejects_img_size_mismatch():
    original = _manifest("sdxl", 1024, [_image(0)])
    growth = _manifest("sdxl", 512, [_image(18)])
    with pytest.raises(ValueError, match="img_size"):
        merge_anchor_manifests([original, growth])


def test_merge_refuses_duplicate_prompt_ids():
    original = _manifest("sdxl", 1024, [_image(0), _image(1)])
    growth = _manifest("sdxl", 1024, [_image(1)])  # re-generated by mistake
    with pytest.raises(ValueError, match="duplicate"):
        merge_anchor_manifests([original, growth])


def test_merge_requires_at_least_one_manifest():
    with pytest.raises(ValueError, match="at least one"):
        merge_anchor_manifests([])
